spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/hw8?createIfNotExist=true
    username: root
    password: root
  mail:
    host: smtp.gmail.com
    username: milansomyk@gmail.com
    password: vapcnbuemszhqbfe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true