spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/hw8?createIfNotExist=true
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.urvydqm.mongodb.net/?retryWrites=true&w=majority
      database: "cars"
jwt:
  signingKey: super_long_secret_key_that_nobody_knows